In [2]:
import pandas as pd

df = pd.read_csv("../data_raw/ecommerce_customer_churn_dataset.csv")
df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,17.9,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,42.8,7.0,3.0,NaN,23.3,3.0,1067.47,3028.0,0,Q4
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,0.0,4.0,1.0,NaN,8.8,NaN,1289.75,2317.0,0,Q4
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,41.4,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1
4,35.0,Male,India,Delhi,3.1,29.0,51.4,NaN,19.1,9.0,...,37.9,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4

In [3]:
missing_ratio = df.isnull().mean().sort_values(ascending=False)
missing_ratio

Social_Media_Engagement_Score    0.12000
Credit_Balance                   0.11000
Mobile_App_Usage                 0.10000
Returns_Rate                     0.08982
Wishlist_Items                   0.08000
Discount_Usage_Rate              0.07000
Product_Reviews_Written          0.07000
Session_Duration_Avg             0.06798
Days_Since_Last_Purchase         0.06000
Pages_Per_Session                0.06000
Email_Open_Rate                  0.05056
Payment_Method_Diversity         0.05000
Age                              0.04990
Customer_Service_Calls           0.00336
Gender                           0.00000
Average_Order_Value              0.00000
Total_Purchases                  0.00000
Cart_Abandonment_Rate            0.00000
Login_Frequency                  0.00000
Membership_Years                 0.00000
City                             0.00000
Lifetime_Value                   0.00000
Country                          0.00000
Churned                          0.00000
Signup_Quarter                   0.00000
dtype: float64

In [4]:
missing_by_churn = df.isnull().groupby(df['Churned']).mean().T
missing_by_churn

Churned                               0         1
Age                            0.052433  0.043668
Gender                         0.000000  0.000000
Country                        0.000000  0.000000
City                           0.000000  0.000000
Membership_Years               0.000000  0.000000
Login_Frequency                0.000000  0.000000
Session_Duration_Avg           0.056287  0.096747
Pages_Per_Session              0.060816  0.057993
Cart_Abandonment_Rate          0.000000  0.000000
Wishlist_Items                 0.079944  0.080138
Total_Purchases                0.000000  0.000000
Average_Order_Value            0.000000  0.000000
Days_Since_Last_Purchase       0.059522  0.061176
Discount_Usage_Rate            0.072574  0.063668
Returns_Rate                   0.088579  0.092872
Email_Open_Rate                0.042194  0.071142
Customer_Service_Calls         0.003038  0.004152
Product_Reviews_Written        0.068889  0.072734
Social_Media_Engagement_Score  0.118678  0.123253
Mobile_App_Usage               0.100225  0.099446
Payment_Method_Diversity       0.050717  0.048235
Lifetime_Value                 0.000000  0.000000
Credit_Balance                 0.109142  0.112111
Churned                        0.000000  0.000000
Signup_Quarter                 0.000000  0.000000

In [5]:
df['Churned'].value_counts(normalize=True)

Churned
0    0.711
1    0.289
Name: proportion, dtype: float64

In [6]:
numeric_cols = df.select_dtypes(include=['float64','int64']).columns
numeric_cols = numeric_cols.drop('Churned')

churn_comparison = df.groupby('Churned')[numeric_cols].mean().T
churn_comparison

Churned                                  0            1
Age                              38.582557    35.902598
Membership_Years                  2.984828     2.981996
Login_Frequency                  12.642391     9.120830
Session_Duration_Avg             29.206784    23.686822
Pages_Per_Session                 9.297002     7.366206
Cart_Abandonment_Rate            54.194460    64.178935
Wishlist_Items                    4.700410     3.309133
Total_Purchases                  13.827522    11.350201
Average_Order_Value             118.383907   134.762532
Days_Since_Last_Purchase         26.892026    36.942135
Discount_Usage_Rate              43.053423    39.424370
Returns_Rate                      6.469185     7.204272
Email_Open_Rate                  22.926396    15.893608
Customer_Service_Calls            5.185458     6.904378
Product_Reviews_Written           3.121839     2.189940
Social_Media_Engagement_Score    31.873633    23.159184
Mobile_App_Usage                 20.710595    16.080266
Payment_Method_Diversity          2.350668     2.361739
Lifetime_Value                 1446.805875  1425.423236
Credit_Balance                 2088.590085  1664.203585

In [7]:
churn_comparison['diff_ratio'] = (
    churn_comparison[1] - churn_comparison[0]
) / churn_comparison[0]

churn_comparison.sort_values('diff_ratio')

Churned                                  0            1  diff_ratio
Email_Open_Rate                  22.926396    15.893608   -0.306755
Product_Reviews_Written           3.121839     2.189940   -0.298510
Wishlist_Items                    4.700410     3.309133   -0.295990
Login_Frequency                  12.642391     9.120830   -0.278552
Social_Media_Engagement_Score    31.873633    23.159184   -0.273406
Mobile_App_Usage                 20.710595    16.080266   -0.223573
Pages_Per_Session                 9.297002     7.366206   -0.207679
Credit_Balance                 2088.590085  1664.203585   -0.203193
Session_Duration_Avg             29.206784    23.686822   -0.188996
Total_Purchases                  13.827522    11.350201   -0.179159
Discount_Usage_Rate              43.053423    39.424370   -0.084292
Age                              38.582557    35.902598   -0.069460
Lifetime_Value                 1446.805875  1425.423236   -0.014779
Membership_Years                  2.984828     2.981996   -0.000949
Payment_Method_Diversity          2.350668     2.361739    0.004710
Returns_Rate                      6.469185     7.204272    0.113629
Average_Order_Value             118.383907   134.762532    0.138352
Cart_Abandonment_Rate            54.194460    64.178935    0.184234
Customer_Service_Calls            5.185458     6.904378    0.331489
Days_Since_Last_Purchase         26.892026    36.942135    0.373721

In [8]:
correlation = df.corr(numeric_only=True)
correlation['Churned'].sort_values(ascending=False)

Churned                          1.000000
Customer_Service_Calls           0.291103
Cart_Abandonment_Rate            0.277963
Days_Since_Last_Purchase         0.153360
Returns_Rate                     0.054189
Average_Order_Value              0.042288
Payment_Method_Diversity         0.004524
Membership_Years                -0.000623
Lifetime_Value                  -0.010684
Discount_Usage_Rate             -0.077121
Age                             -0.102849
Credit_Balance                  -0.156921
Total_Purchases                 -0.160029
Product_Reviews_Written         -0.181225
Social_Media_Engagement_Score   -0.191792
Wishlist_Items                  -0.197708
Login_Frequency                 -0.204379
Email_Open_Rate                 -0.222213
Mobile_App_Usage                -0.222876
Session_Duration_Avg            -0.228010
Pages_Per_Session               -0.231799
Name: Churned, dtype: float64

In [10]:
df['recency_bin'] = pd.qcut(df['Days_Since_Last_Purchase'], 5)

df.groupby('recency_bin')['Churned'].mean()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_29156\3738668337.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('recency_bin')['Churned'].mean()

recency_bin
(-0.001, 7.0]    0.224002
(7.0, 15.0]      0.245984
(15.0, 27.0]     0.271301
(27.0, 48.0]     0.303283
(48.0, 287.0]    0.403739
Name: Churned, dtype: float64

In [11]:
df['login_bin'] = pd.qcut(df['Login_Frequency'], 5)

df.groupby('login_bin')['Churned'].mean()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_29156\4126209723.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('login_bin')['Churned'].mean()

login_bin
(-0.001, 4.0]    0.473513
(4.0, 9.0]       0.307328
(9.0, 13.0]      0.240295
(13.0, 18.0]     0.215653
(18.0, 46.0]     0.192129
Name: Churned, dtype: float64

In [12]:
df['call_bin'] = pd.qcut(df['Customer_Service_Calls'], 5)
df.groupby('call_bin')['Churned'].mean()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_29156\717161094.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('call_bin')['Churned'].mean()

call_bin
(-0.001, 3.0]    0.124977
(3.0, 5.0]       0.170597
(5.0, 6.0]       0.397256
(6.0, 8.0]       0.411345
(8.0, 21.0]      0.481926
Name: Churned, dtype: float64

In [13]:
df['aov_bin'] = pd.qcut(df['Average_Order_Value'], 5)
df.groupby('aov_bin')['Churned'].mean()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_29156\1789618764.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('aov_bin')['Churned'].mean()

aov_bin
(26.378999999999998, 81.448]    0.211700
(81.448, 102.62]                0.241727
(102.62, 124.18]                0.266953
(124.18, 153.414]               0.312831
(153.414, 9666.379]             0.411800
Name: Churned, dtype: float64

In [14]:
df['risk_user'] = (
    (df['Customer_Service_Calls'] >= 5) &
    (df['Days_Since_Last_Purchase'] >= 30)
).astype(int)

df.groupby('risk_user')['Churned'].mean()

risk_user
0    0.240080
1    0.459688
Name: Churned, dtype: float64